package it.randyflow.controller;

import it.randyflow.dto.*; import it.randyflow.dto.ApiDtos.*; import it.randyflow.service.*; import jakarta.validation.Valid; import java.util.*; import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;

@RestController @RequestMapping("/api/v1") public class ApiController {
 private final CoreService core;private final PlannerService planner;private final LearningService learning;private final StudyPackageService packages;private final StatsService stats;
 public ApiController(CoreService core,PlannerService planner,LearningService learning,StudyPackageService packages,StatsService stats){this.core=core;this.planner=planner;this.learning=learning;this.packages=packages;this.stats=stats;}
 @GetMapping("/exams") List<ExamDto> exams(){return core.exams();}@GetMapping("/exams/{id}") ExamDto exam(@PathVariable String id){return core.exam(id);}@PostMapping("/exams") ExamDto create(@Valid @RequestBody NewExam input){return core.create(input);}
 @GetMapping("/documents") List<MaterialDto> documents(){return core.materials();}@GetMapping("/documents/{id}") MaterialDto document(@PathVariable String id){return core.material(id);}@PatchMapping("/documents/{id}/position") MaterialDto position(@PathVariable String id,@Valid @RequestBody Position input){return core.position(id,input.page());}@PostMapping("/documents/{id}/pages/{page}/complete") @ResponseStatus(HttpStatus.NO_CONTENT) void complete(@PathVariable String id,@PathVariable int page,@RequestBody(required=false) Completion input){core.complete(id,page,input==null?null:input.sessionId());}
 @GetMapping("/documents/{id}/pages/{page}") Map<String,Object> slide(@PathVariable String id,@PathVariable int page){return core.slide(id,page);}@GetMapping("/documents/{id}/thumbnails") List<Map<String,Object>> thumbnails(@PathVariable String id){return core.thumbnails(id);}@GetMapping("/documents/{id}/search") List<Map<String,Object>> search(@PathVariable String id,@RequestParam String q){return core.search(id,q);}
 @PostMapping(value="/exams/{examId}/materials",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) MaterialDto upload(@PathVariable String examId,@RequestPart("file")MultipartFile file){return core.upload(examId,file);}@GetMapping(value="/documents/{id}/file",produces=MediaType.APPLICATION_PDF_VALUE) Resource pdf(@PathVariable String id){return core.pdf(id);}
 @PostMapping("/study-logs") StudyLogDto log(@Valid @RequestBody StudyLogInput input){return core.log(input);}@GetMapping("/study-logs") List<StudyLogDto> logs(){return core.logs();}
 @GetMapping("/sessions") List<SessionDto> sessions(@RequestParam(required=false)String examId){return planner.sessions(examId);}@PostMapping("/exams/{id}/plan/recalculate") List<SessionDto> recalculate(@PathVariable String id){return planner.recalculate(id);}@PatchMapping("/sessions/{session}/tasks/{task}") SessionDto toggle(@PathVariable String session,@PathVariable String task){return planner.toggle(session,task);}@PostMapping("/sessions/{id}/report") Map<String,Object> report(@PathVariable String id,@RequestBody Map<String,Object> body){return planner.report(id,String.valueOf(body.get("outcome")),body.get("slidesDone")instanceof Number n?n.intValue():null);}@PatchMapping("/exams/{id}/availability") ExamDto availability(@PathVariable String id,@RequestBody Map<String,Map<Integer,Integer>> body){return planner.availability(id,body.get("availability"));}
 @GetMapping("/today") Map<String,Object> today(){var exams=core.exams();if(exams.isEmpty())throw it.randyflow.exception.ApiException.notFound("Nessun esame disponibile");var exam=exams.get(0);var docs=core.materials().stream().filter(d->d.examId().equals(exam.id())).toList();if(docs.isEmpty())throw it.randyflow.exception.ApiException.notFound("Nessun materiale disponibile");var all=planner.sessions(exam.id());var current=all.stream().filter(s->s.date().equals(java.time.LocalDate.now())).findFirst().orElse(null);return new java.util.HashMap<>(Map.of("exam",exam,"document",docs.get(0),"daysLeft",Math.max(0,java.time.temporal.ChronoUnit.DAYS.between(java.time.LocalDate.now(),exam.date())),"plannedMinutes",current==null?0:current.durationMin(),"upcoming",all.stream().filter(s->s.date().isAfter(java.time.LocalDate.now())).limit(4).toList(),"progress",exam.totalSlides()==0?0d:exam.slidesCompleted()/(double)exam.totalSlides(),"forecastDaysEarly",0,"adjustment",Optional.empty(),"session",Optional.ofNullable(current)));}
 @GetMapping("/exams/{id}/quiz") List<QuizDto> quiz(@PathVariable String id){return learning.quiz(id);}@PostMapping("/exams/{id}/quiz") List<MasteryDto> quiz(@PathVariable String id,@Valid @RequestBody QuizSubmission input){return learning.submitQuiz(id,input);}@GetMapping("/exams/{id}/flashcards") List<FlashcardDto> cards(@PathVariable String id){return learning.flashcards(id);}@PostMapping("/exams/{exam}/flashcards/{id}/ratings") @ResponseStatus(HttpStatus.NO_CONTENT) void rate(@PathVariable String exam,@PathVariable String id,@Valid @RequestBody Rating input){learning.review(exam,id,input.rating());}@GetMapping("/mastery") List<MasteryDto> mastery(@RequestParam(required=false)String examId){return learning.mastery(examId);}@PostMapping("/exams/{id}/simulation") MasteryDto simulation(@PathVariable String id,@Valid @RequestBody SimulationInput input){return learning.simulation(id,input);}
 @GetMapping("/study-packages") List<StudyPackageDto> packageList(){return packages.list();}@GetMapping("/study-packages/exams/{id}") StudyPackageDto packageExam(@PathVariable String id){return packages.getByExam(id);}@GetMapping("/study-packages/materials/{id}") StudyPackageDto packageMaterial(@PathVariable String id){return packages.getByMaterial(id);}@PostMapping("/study-packages/preview") PackagePreview preview(@Valid @RequestBody StudyPackageDto input){return packages.preview(write(input));}@PostMapping("/study-packages/import") PackageSummary importPackage(@Valid @RequestBody StudyPackageDto input){return packages.importPackage(input);}
 @GetMapping("/stats") StatsDto stats(){return stats.get();}@GetMapping("/me") ProfileDto me(){return core.profile();}@PatchMapping("/me") ProfileDto me(@RequestBody ProfileDto input){return core.profile(input);}@GetMapping("/settings") PreferenceDto settings(){return core.preferences();}@PatchMapping("/settings") PreferenceDto settings(@RequestBody PreferenceDto input){return core.preferences(input);}
 @GetMapping("/adjustments") List<Object> adjustments(){return List.of();}@PostMapping("/adjustments/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void adjustment(@PathVariable String id){}@GetMapping("/notifications") List<Object> notifications(){return List.of();}@PostMapping("/notifications/read") @ResponseStatus(HttpStatus.NO_CONTENT) void notificationsRead(){}
 private String write(Object value){try{return new com.fasterxml.jackson.databind.ObjectMapper().findAndRegisterModules().writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
}
