CREATE TABLE exams (
  id VARCHAR(120) PRIMARY KEY, name VARCHAR(255) NOT NULL, short_name VARCHAR(16) NOT NULL,
  exam_date DATE, description TEXT, status VARCHAR(32) NOT NULL DEFAULT 'not-started',
  total_slides INTEGER NOT NULL DEFAULT 0, slides_completed INTEGER NOT NULL DEFAULT 0,
  minutes_studied INTEGER NOT NULL DEFAULT 0, review_days INTEGER NOT NULL DEFAULT 4,
  availability_json TEXT NOT NULL DEFAULT '{}', unavailable_days_json TEXT NOT NULL DEFAULT '[]',
  created_at DATE NOT NULL
);
CREATE TABLE study_packages (
  package_id VARCHAR(160) PRIMARY KEY, exam_id VARCHAR(120) NOT NULL UNIQUE REFERENCES exams(id),
  version VARCHAR(16) NOT NULL, revision INTEGER NOT NULL, generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  language VARCHAR(16) NOT NULL, raw_json TEXT NOT NULL, imported_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE study_materials (
  id VARCHAR(160) PRIMARY KEY, exam_id VARCHAR(120) NOT NULL REFERENCES exams(id), name VARCHAR(255) NOT NULL,
  material_type VARCHAR(24) NOT NULL, page_count INTEGER NOT NULL, last_page INTEGER NOT NULL DEFAULT 1,
  pages_read INTEGER NOT NULL DEFAULT 0, completed_pages_json TEXT NOT NULL DEFAULT '[]',
  chapters_json TEXT NOT NULL DEFAULT '[]', storage_path TEXT, mime_type VARCHAR(120), file_size BIGINT,
  updated_at DATE NOT NULL
);
CREATE TABLE topics (
  id VARCHAR(160) PRIMARY KEY, material_id VARCHAR(160) NOT NULL REFERENCES study_materials(id), name VARCHAR(255) NOT NULL,
  slide_from INTEGER NOT NULL, slide_to INTEGER NOT NULL, difficulty INTEGER NOT NULL, importance INTEGER NOT NULL,
  estimated_minutes INTEGER NOT NULL, simple_explanation TEXT NOT NULL, normal_explanation TEXT NOT NULL,
  deep_explanation TEXT NOT NULL, summary TEXT NOT NULL, key_concepts_json TEXT NOT NULL, examples_json TEXT NOT NULL
);
CREATE TABLE quizzes (
  id VARCHAR(160) PRIMARY KEY, topic_id VARCHAR(160) NOT NULL REFERENCES topics(id), quiz_type VARCHAR(24) NOT NULL,
  prompt TEXT NOT NULL, options_json TEXT, correct_answer TEXT NOT NULL, accepted_keywords_json TEXT,
  explanation TEXT NOT NULL, slide_refs_json TEXT NOT NULL
);
CREATE TABLE flashcards (
  id VARCHAR(160) PRIMARY KEY, topic_id VARCHAR(160) NOT NULL REFERENCES topics(id), front TEXT NOT NULL,
  back TEXT NOT NULL, slide_refs_json TEXT NOT NULL
);
CREATE TABLE exam_questions (
  id VARCHAR(160) PRIMARY KEY, topic_id VARCHAR(160) NOT NULL REFERENCES topics(id), prompt TEXT NOT NULL,
  model_answer TEXT NOT NULL, evaluation_criteria_json TEXT NOT NULL, slide_refs_json TEXT NOT NULL
);
CREATE TABLE study_plans (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, exam_id VARCHAR(120) NOT NULL REFERENCES exams(id), generated_at TIMESTAMP WITH TIME ZONE NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE study_sessions (
  id VARCHAR(180) PRIMARY KEY, plan_id BIGINT REFERENCES study_plans(id), exam_id VARCHAR(120) NOT NULL REFERENCES exams(id),
  session_date DATE NOT NULL, status VARCHAR(32) NOT NULL, topic VARCHAR(500), slide_from INTEGER, slide_to INTEGER,
  slides_done INTEGER, next_page INTEGER, duration_min INTEGER NOT NULL, previous_duration_min INTEGER, note TEXT
);
CREATE TABLE study_tasks (
  id VARCHAR(220) PRIMARY KEY, session_id VARCHAR(180) NOT NULL REFERENCES study_sessions(id) ON DELETE CASCADE,
  task_kind VARCHAR(32) NOT NULL, label VARCHAR(500) NOT NULL, duration_min INTEGER NOT NULL, done BOOLEAN NOT NULL DEFAULT FALSE, meta TEXT
);
CREATE TABLE quiz_attempts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, exam_id VARCHAR(120) NOT NULL REFERENCES exams(id), question_id VARCHAR(160) NOT NULL, correct BOOLEAN NOT NULL, given_answer TEXT, attempted_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE flashcard_reviews (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, exam_id VARCHAR(120) NOT NULL REFERENCES exams(id), flashcard_id VARCHAR(160) NOT NULL, rating VARCHAR(24) NOT NULL, reviewed_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE topic_mastery (topic_id VARCHAR(160) PRIMARY KEY, exam_id VARCHAR(120) NOT NULL REFERENCES exams(id), topic_name VARCHAR(255) NOT NULL, score INTEGER NOT NULL DEFAULT 0, trend VARCHAR(16) NOT NULL DEFAULT 'flat', needs_review BOOLEAN NOT NULL DEFAULT TRUE, slide_from INTEGER NOT NULL, slide_to INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE exam_simulations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, exam_id VARCHAR(120) NOT NULL REFERENCES exams(id), question_id VARCHAR(160) NOT NULL, answer TEXT NOT NULL, rating INTEGER NOT NULL, submitted_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE study_logs (id VARCHAR(160) PRIMARY KEY, exam_id VARCHAR(120) NOT NULL REFERENCES exams(id), material_id VARCHAR(160) NOT NULL REFERENCES study_materials(id), log_date DATE NOT NULL, from_page INTEGER NOT NULL, to_page INTEGER NOT NULL, minutes INTEGER NOT NULL, label VARCHAR(500) NOT NULL);
CREATE TABLE user_profiles (id VARCHAR(64) PRIMARY KEY, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, email VARCHAR(255) NOT NULL, university VARCHAR(255), course VARCHAR(255), study_year VARCHAR(64), initials VARCHAR(12));
CREATE TABLE user_preferences (id VARCHAR(64) PRIMARY KEY, session_minutes INTEGER NOT NULL, break_minutes INTEGER NOT NULL, notifications BOOLEAN NOT NULL, auto_break BOOLEAN NOT NULL, explanation_level VARCHAR(32) NOT NULL);
CREATE INDEX idx_material_exam ON study_materials(exam_id); CREATE INDEX idx_topic_material ON topics(material_id); CREATE INDEX idx_session_exam_date ON study_sessions(exam_id, session_date); CREATE INDEX idx_attempt_exam ON quiz_attempts(exam_id); CREATE INDEX idx_review_exam ON flashcard_reviews(exam_id);
