CREATE TABLE app_users (
  id VARCHAR(64) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE auth_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO app_users(id, email, password_hash, created_at)
VALUES ('local', 'studente@example.com', 'ACCOUNT_LEGACY_NON_ACCESSIBILE', CURRENT_TIMESTAMP);

ALTER TABLE exams ADD COLUMN owner_id VARCHAR(64);
UPDATE exams SET owner_id = 'local' WHERE owner_id IS NULL;
ALTER TABLE exams ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE exams ADD CONSTRAINT fk_exam_owner FOREIGN KEY (owner_id) REFERENCES app_users(id);
CREATE INDEX idx_exam_owner ON exams(owner_id);
CREATE INDEX idx_auth_session_token ON auth_sessions(token_hash);

