spring:
  application.name: randyflow-backend
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
  servlet.multipart:
    max-file-size: 50MB
    max-request-size: 50MB
  flyway.locations: classpath:db/migration
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /v3/api-docs
server:
  port: ${SERVER_PORT:8080}
randyflow:
  storage-path: ${STORAGE_PATH:./storage}
  cors-origin: ${CORS_ORIGIN:http://localhost:3000}
