package it.randyflow.service;
import it.randyflow.domain.*; import it.randyflow.dto.ApiDtos.ProfileDto; import it.randyflow.dto.AuthDtos.*; import it.randyflow.exception.ApiException; import it.randyflow.repository.*; import jakarta.transaction.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service;
@Service public class AuthService {
 private final AppUserRepository users; private final AuthSessionRepository sessions; private final ApplicationRepository data; private final PasswordEncoder passwords;
 public AuthService(AppUserRepository users,AuthSessionRepository sessions,ApplicationRepository data,PasswordEncoder passwords){this.users=users;this.sessions=sessions;this.data=data;this.passwords=passwords;}
 @Transactional public AuthResponse register(RegisterRequest in){String email=in.email().trim().toLowerCase(Locale.ROOT);if(users.findByEmailIgnoreCase(email).isPresent())throw ApiException.conflict("Esiste già un account con questa email");AppUserEntity user=new AppUserEntity();user.id=UUID.randomUUID().toString();user.email=email;user.passwordHash=passwords.encode(in.password());user.createdAt=OffsetDateTime.now();users.save(user);UserProfileEntity profile=new UserProfileEntity();profile.id=user.id;profile.firstName=in.firstName().trim();profile.lastName=in.lastName().trim();profile.email=email;profile.university="";profile.course="";profile.studyYear="";profile.initials=initials(profile.firstName,profile.lastName);data.save(profile);UserPreferenceEntity prefs=new UserPreferenceEntity();prefs.id=user.id;prefs.sessionMinutes=25;prefs.breakMinutes=5;prefs.notifications=true;prefs.autoBreak=true;prefs.explanationLevel="Normale";data.save(prefs);return issue(user,profile);}
 @Transactional public AuthResponse login(LoginRequest in){AppUserEntity user=users.findByEmailIgnoreCase(in.email().trim()).orElseThrow(()->ApiException.unauthorized("Email o password non corretti"));if(!passwords.matches(in.password(),user.passwordHash))throw ApiException.unauthorized("Email o password non corretti");return issue(user,data.profile(user.id));}
 @Transactional public void logout(String rawToken){if(rawToken!=null&&!rawToken.isBlank())sessions.deleteByTokenHash(hash(rawToken));}
 public Optional<String> authenticate(String rawToken){if(rawToken==null||rawToken.isBlank())return Optional.empty();return sessions.findByTokenHashAndExpiresAtAfter(hash(rawToken),OffsetDateTime.now()).map(s->s.userId);}
 private AuthResponse issue(AppUserEntity user,UserProfileEntity profile){String token=randomToken();AuthSessionEntity session=new AuthSessionEntity();session.userId=user.id;session.tokenHash=hash(token);session.createdAt=OffsetDateTime.now();session.expiresAt=session.createdAt.plusDays(30);sessions.save(session);return new AuthResponse(token,new ProfileDto(profile.id,profile.firstName,profile.lastName,profile.email,profile.university,profile.course,profile.studyYear,profile.initials));}
 private String randomToken(){byte[] bytes=new byte[32];new SecureRandom().nextBytes(bytes);return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);}
 private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private String initials(String first,String last){return (first.substring(0,1)+last.substring(0,1)).toUpperCase(Locale.ROOT);}
}
