package it.randyflow.service;

import com.fasterxml.jackson.core.type.TypeReference; import it.randyflow.domain.*; import it.randyflow.dto.ApiDtos.*; import it.randyflow.exception.ApiException; import it.randyflow.mapper.EntityMapper; import it.randyflow.repository.*; import it.randyflow.security.UserContext; import jakarta.transaction.Transactional; import java.io.*; import java.time.*; import java.util.*; import org.apache.pdfbox.Loader; import org.springframework.core.io.*; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile;

@Service public class CoreService {
 private final ExamRepository exams;private final StudyMaterialRepository materials;private final TopicRepository topics;private final ApplicationRepository data;private final EntityMapper mapper;private final PlannerService planner;private final MaterialStorageService storage;private final UserContext users;
 public CoreService(ExamRepository exams,StudyMaterialRepository materials,TopicRepository topics,ApplicationRepository data,EntityMapper mapper,PlannerService planner,MaterialStorageService storage,UserContext users){this.exams=exams;this.materials=materials;this.topics=topics;this.data=data;this.mapper=mapper;this.planner=planner;this.storage=storage;this.users=users;}
 public List<ExamDto> exams(){return exams.findByOwnerIdOrderByCreatedAtDesc(users.idOrLegacy()).stream().map(this::exam).toList();} public ExamDto exam(String id){return exam(requireExam(id));} private ExamDto exam(ExamEntity e){return mapper.exam(e,materials.findByExamId(e.id).stream().map(m->m.id).toList());}
 @Transactional public ExamDto create(NewExam in){ExamEntity e=new ExamEntity();e.id="exam-"+UUID.randomUUID();e.ownerId=users.idOrLegacy();e.name=in.name();e.shortName=in.name().substring(0,Math.min(3,in.name().length())).toUpperCase();e.examDate=in.date();e.description=in.description();e.reviewDays=in.reviewDays();e.availabilityJson=mapper.write(in.availability());e.unavailableDaysJson=mapper.write(in.unavailableDays());e.createdAt=LocalDate.now();exams.save(e);int index=0;for(var d:in.documents()){StudyMaterialEntity m=new StudyMaterialEntity();m.id="doc-"+e.id+(index++==0?"":"-"+index);m.examId=e.id;m.name=d.name();m.materialType="pdf";m.pageCount=d.pages();m.updatedAt=LocalDate.now();materials.save(m);e.totalSlides+=d.pages();}exams.save(e);planner.recalculate(e.id);return exam(e);}
 @Transactional public void deleteExam(String id){ExamEntity exam=requireExam(id);for(var material:materials.findByExamId(id))if(material.storagePath!=null)storage.delete(material.storagePath);data.deleteExamGraph(id);exams.delete(exam);}
 public List<MaterialDto> materials(){var ids=ownedExamIds();return materials.findAll().stream().filter(m->ids.contains(m.examId)).map(mapper::material).toList();} public MaterialDto material(String id){return mapper.material(materials.findById(id).orElseThrow(()->ApiException.notFound("Materiale non trovato")));}
 public Map<String,Object> slide(String id,int page){StudyMaterialEntity m=materialEntity(id);if(page<1||page>m.pageCount)throw ApiException.badRequest("Pagina non valida");TopicEntity t=topics.findByMaterialIdIn(List.of(id)).stream().filter(x->page>=x.slideFrom&&page<=x.slideTo).findFirst().orElse(null);String title=t==null?"Slide "+page:t.name;List<String> bullets=t==null?List.of("Apri il PDF originale per consultare questa pagina."):mapper.read(t.keyConceptsJson,new TypeReference<List<String>>(){});return Map.of("number",page,"chapter",title,"title",title,"kind","bullets","bullets",bullets);}
 public List<Map<String,Object>> thumbnails(String id){StudyMaterialEntity m=materialEntity(id);return java.util.stream.IntStream.rangeClosed(1,m.pageCount).mapToObj(page->slide(id,page)).toList();}
 public List<Map<String,Object>> search(String id,String query){String needle=query.toLowerCase(Locale.ROOT);StudyMaterialEntity m=materialEntity(id);return java.util.stream.IntStream.rangeClosed(1,m.pageCount).mapToObj(page->slide(id,page)).filter(s->s.toString().toLowerCase(Locale.ROOT).contains(needle)).map(s->Map.<String,Object>of("page",s.get("number"),"title",s.get("title"))).toList();}
 @Transactional public MaterialDto position(String id,int page){StudyMaterialEntity m=materialEntity(id);m.lastPage=Math.max(1,Math.min(m.pageCount,page));return mapper.material(materials.save(m));}
 @Transactional public void complete(String id,int page,String sessionId){StudyMaterialEntity m=materialEntity(id);if(page<1||page>m.pageCount)throw ApiException.badRequest("Pagina non valida");Set<Integer> done=new TreeSet<>(mapper.read(m.completedPagesJson,new TypeReference<List<Integer>>(){}));if(done.add(page)){m.completedPagesJson=mapper.write(done);m.pagesRead=done.size();materials.save(m);ExamEntity e=requireExam(m.examId);e.slidesCompleted=materials.findByExamId(e.id).stream().mapToInt(x->x.pagesRead).sum();exams.save(e);}if(sessionId!=null){StudySessionEntity s=data.session(sessionId);if(s!=null){requireExam(s.examId);}if(s!=null&&s.slideFrom!=null&&s.slideTo!=null){s.slidesDone=(int)done.stream().filter(n->n>=s.slideFrom&&n<=s.slideTo).count();s.nextPage=java.util.stream.IntStream.rangeClosed(s.slideFrom,s.slideTo).filter(n->!done.contains(n)).boxed().findFirst().orElse(s.slideTo);data.save(s);}}}
 @Transactional public StudyLogDto log(StudyLogInput in){ExamEntity e=requireExam(in.examId());StudyMaterialEntity ownedMaterial=materialEntity(in.documentId());if(!ownedMaterial.examId.equals(e.id))throw ApiException.badRequest("Materiale non appartenente all?esame");StudyLogEntity l=new StudyLogEntity();l.id=UUID.randomUUID().toString();l.examId=in.examId();l.materialId=in.documentId();l.logDate=LocalDate.now();l.fromPage=in.fromPage();l.toPage=in.toPage();l.minutes=in.minutes();l.label=in.label();data.save(l);e.minutesStudied+=in.minutes();exams.save(e);return logDto(l);}
 public List<StudyLogDto> logs(){return data.logs(ownedExamIds()).stream().map(this::logDto).toList();}private StudyLogDto logDto(StudyLogEntity l){return new StudyLogDto(l.id,l.examId,l.materialId,l.logDate,l.fromPage,l.toPage,l.minutes,l.label);}
 @Transactional public MaterialDto upload(String examId,MultipartFile file){if(file.isEmpty()||!("application/pdf".equalsIgnoreCase(file.getContentType())||Optional.ofNullable(file.getOriginalFilename()).orElse("").toLowerCase(Locale.ROOT).endsWith(".pdf")))throw ApiException.badRequest("Ãˆ richiesto un PDF valido");ExamEntity e=requireExam(examId);try{String name=Optional.ofNullable(file.getOriginalFilename()).orElse("materiale.pdf");StudyMaterialEntity m=materials.findByExamId(examId).stream().filter(x->x.storagePath==null&&x.name.equals(name)).findFirst().orElseGet(StudyMaterialEntity::new);boolean existing=m.id!=null;int previous=existing?m.pageCount:0;if(!existing){m.id="pdf-"+UUID.randomUUID();m.examId=e.id;m.name=name;m.materialType="pdf";}byte[] bytes=file.getBytes();int pages;try(var pdf=Loader.loadPDF(bytes)){pages=pdf.getNumberOfPages();}m.storagePath=storage.store(m.id,bytes);m.pageCount=pages;m.mimeType="application/pdf";m.fileSize=file.getSize();m.updatedAt=LocalDate.now();materials.save(m);e.totalSlides=e.totalSlides-previous+pages;exams.save(e);return mapper.material(m);}catch(IOException|IllegalStateException x){throw ApiException.badRequest("PDF non leggibile o storage non disponibile");}}
 public Map<String,Object> inspect(MultipartFile file){if(file.isEmpty()||!("application/pdf".equalsIgnoreCase(file.getContentType())||Optional.ofNullable(file.getOriginalFilename()).orElse("").toLowerCase(Locale.ROOT).endsWith(".pdf")))throw ApiException.badRequest("È richiesto un PDF valido");try{byte[] bytes=file.getBytes();try(var pdf=Loader.loadPDF(bytes)){return Map.of("name",Optional.ofNullable(file.getOriginalFilename()).orElse("materiale.pdf"),"pages",pdf.getNumberOfPages(),"bytes",file.getSize());}}catch(IOException e){throw ApiException.badRequest("PDF non leggibile");}}
 public Resource pdf(String id){StudyMaterialEntity m=materialEntity(id);if(m.storagePath==null)throw ApiException.notFound("PDF non caricato");return storage.load(m.storagePath,m.name);}
 private StudyMaterialEntity materialEntity(String id){var m=materials.findById(id).orElseThrow(()->ApiException.notFound("Materiale non trovato"));requireExam(m.examId);return m;}
 private ExamEntity requireExam(String id){return exams.findByIdAndOwnerId(id,users.idOrLegacy()).orElseThrow(()->ApiException.notFound("Esame non trovato"));}
 private List<String> ownedExamIds(){return exams.findByOwnerIdOrderByCreatedAtDesc(users.idOrLegacy()).stream().map(e->e.id).toList();}
 public ProfileDto profile(){var p=data.profile(users.idOrLegacy());return new ProfileDto(p.id,p.firstName,p.lastName,p.email,p.university,p.course,p.studyYear,p.initials);}@Transactional public ProfileDto profile(ProfileDto x){var p=data.profile(users.idOrLegacy());p.firstName=x.firstName();p.lastName=x.lastName();p.email=x.email();p.university=x.university();p.course=x.course();p.studyYear=x.year();p.initials=x.initials();data.save(p);return profile();}
 public PreferenceDto preferences(){var p=data.preferences(users.idOrLegacy());return new PreferenceDto(p.sessionMinutes,p.breakMinutes,p.notifications,p.autoBreak,p.explanationLevel);}@Transactional public PreferenceDto preferences(PreferenceDto x){var p=data.preferences(users.idOrLegacy());p.sessionMinutes=x.sessionMinutes();p.breakMinutes=x.breakMinutes();p.notifications=x.notifications();p.autoBreak=x.autoBreak();p.explanationLevel=x.explanationLevel();data.save(p);return preferences();}
}
