package it.randyflow.service;

import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import it.randyflow.domain.*; import it.randyflow.dto.ApiDtos.*; import it.randyflow.exception.ApiException; import it.randyflow.mapper.EntityMapper; import it.randyflow.repository.*; import it.randyflow.security.UserContext; import jakarta.transaction.Transactional; import java.time.*; import java.util.*; import org.springframework.stereotype.Service;

@Service public class LearningService {
 private final QuizRepository quizzes;private final FlashcardRepository cards;private final ExamQuestionRepository questions;private final TopicRepository topics;private final StudyMaterialRepository materials;private final ApplicationRepository data;private final EntityMapper mapper;private final ObjectMapper json;private final ExamRepository exams;private final UserContext users;
 public LearningService(QuizRepository quizzes,FlashcardRepository cards,ExamQuestionRepository questions,TopicRepository topics,StudyMaterialRepository materials,ApplicationRepository data,EntityMapper mapper,ObjectMapper json,ExamRepository exams,UserContext users){this.quizzes=quizzes;this.cards=cards;this.questions=questions;this.topics=topics;this.materials=materials;this.data=data;this.mapper=mapper;this.json=json;this.exams=exams;this.users=users;}
 private List<TopicEntity> examTopics(String exam){requireExam(exam);return topics.findByMaterialIdIn(materials.findByExamId(exam).stream().map(m->m.id).toList());}
 public List<QuizDto> quiz(String exam){List<TopicEntity> ts=examTopics(exam);Map<String,TopicEntity> byId=new HashMap<>();ts.forEach(t->byId.put(t.id,t));return quizzes.findByTopicIdIn(byId.keySet()).stream().map(q->{TopicEntity t=byId.get(q.topicId);List<String> opts=read(q.optionsJson,new TypeReference<>(){});List<String> keys=read(q.acceptedKeywordsJson,new TypeReference<>(){});List<Integer> refs=read(q.slideRefsJson,new TypeReference<>(){});Integer correct="multiple".equals(q.quizType)?Integer.valueOf(q.correctAnswer):null;String model="open".equals(q.quizType)?unquote(q.correctAnswer):null;return new QuizDto(q.id,q.quizType,q.prompt,opts,correct,keys,model,q.explanation,refs.get(0),t.id,t.name);}).toList();}
 @Transactional public List<MasteryDto> submitQuiz(String exam,QuizSubmission input){Map<String,QuizEntity> available=new HashMap<>();for(var q:quizzes.findByTopicIdIn(examTopics(exam).stream().map(t->t.id).toList()))available.put(q.id,q);for(var answer:input.answers()){QuizEntity q=available.get(answer.questionId());if(q==null)throw ApiException.badRequest("Domanda non appartenente all’esame");QuizAttemptEntity a=new QuizAttemptEntity();a.examId=exam;a.questionId=q.id;a.correct=answer.correct();a.givenAnswer=answer.given();a.attemptedAt=OffsetDateTime.now();data.save(a);updateMastery(q.topicId,answer.correct()?100:0);}return mastery(exam);}
 public List<FlashcardDto> flashcards(String exam){Map<String,TopicEntity> byId=new HashMap<>();examTopics(exam).forEach(t->byId.put(t.id,t));return cards.findByTopicIdIn(byId.keySet()).stream().map(c->new FlashcardDto(c.id,c.front,c.back,read(c.slideRefsJson,new TypeReference<List<Integer>>(){}).get(0),byId.get(c.topicId).name)).toList();}
 @Transactional public void review(String exam,String id,String rating){requireExam(exam);FlashcardEntity c=cards.findById(id).filter(x->examTopics(exam).stream().anyMatch(t->t.id.equals(x.topicId))).orElseThrow(()->ApiException.notFound("Flashcard non trovata"));FlashcardReviewEntity r=new FlashcardReviewEntity();r.examId=exam;r.flashcardId=id;r.rating=rating;r.reviewedAt=OffsetDateTime.now();data.save(r);updateMastery(c.topicId,Map.of("unknown",0,"hard",45,"known",100).getOrDefault(rating,0));}
 public List<MasteryDto> mastery(String exam){if(exam!=null)requireExam(exam);return data.mastery(exam,ownedExamIds()).stream().map(mapper::mastery).toList();}
 @Transactional public MasteryDto simulation(String exam,SimulationInput input){requireExam(exam);ExamQuestionEntity q=questions.findById(input.questionId()).filter(x->examTopics(exam).stream().anyMatch(t->t.id.equals(x.topicId))).orElseThrow(()->ApiException.notFound("Domanda d’esame non trovata"));ExamSimulationEntity s=new ExamSimulationEntity();s.examId=exam;s.questionId=q.id;s.answer=input.answer();s.rating=input.rating();s.submittedAt=OffsetDateTime.now();data.save(s);return mapper.mastery(updateMastery(q.topicId,input.rating()));}
 private TopicMasteryEntity updateMastery(String topicId,int value){TopicEntity t=topics.findById(topicId).orElseThrow();TopicMasteryEntity m=data.masteryById(topicId);if(m==null){m=new TopicMasteryEntity();m.topicId=t.id;m.examId=materials.findById(t.materialId).orElseThrow().examId;m.topicName=t.name;m.slideFrom=t.slideFrom;m.slideTo=t.slideTo;}int next=Math.round(m.score*.7f+value*.3f);m.trend=next>m.score?"up":next<m.score?"down":"flat";m.score=next;m.attempts++;m.needsReview=next<60;return data.save(m);}
 private <T>T read(String value,TypeReference<T> type){if(value==null)return null;return mapper.read(value,type);}private String unquote(String value){try{return json.readValue(value,String.class);}catch(Exception e){return value;}}
 private void requireExam(String id){if(exams.findByIdAndOwnerId(id,users.idOrLegacy()).isEmpty())throw ApiException.notFound("Esame non trovato");}
 private List<String> ownedExamIds(){return exams.findByOwnerIdOrderByCreatedAtDesc(users.idOrLegacy()).stream().map(e->e.id).toList();}
}
