package it.randyflow.service;

import it.randyflow.domain.*; import it.randyflow.dto.ApiDtos.*; import it.randyflow.exception.ApiException; import it.randyflow.repository.*; import it.randyflow.security.UserContext; import jakarta.transaction.Transactional; import java.time.*; import java.util.*; import org.springframework.stereotype.Service;

@Service public class PlannerService {
 private final ApplicationRepository data; private final ExamRepository exams; private final StudyMaterialRepository materials; private final TopicRepository topics; private final UserContext users;
 public PlannerService(ApplicationRepository data,ExamRepository exams,StudyMaterialRepository materials,TopicRepository topics,UserContext users){this.data=data;this.exams=exams;this.materials=materials;this.topics=topics;this.users=users;}
 @Transactional public List<SessionDto> recalculate(String examId){ExamEntity exam=requireExam(examId);StudyMaterialEntity material=materials.findByExamId(examId).stream().findFirst().orElseThrow(()->ApiException.badRequest("Materiale mancante"));data.deleteFuturePlan(examId);StudyPlanEntity plan=new StudyPlanEntity();plan.examId=examId;plan.generatedAt=OffsetDateTime.now();data.save(plan);LocalDate start=LocalDate.now().plusDays(1), end=exam.examDate.minusDays(Math.max(0,exam.reviewDays));int first=Math.max(1,exam.slidesCompleted+1);List<LocalDate> days=start.datesUntil(end.plusDays(1)).filter(d->d.getDayOfWeek()!=DayOfWeek.SUNDAY).toList();int cursor=first;for(int i=0;i<days.size()&&cursor<=material.pageCount;i++){int slots=days.size()-i;int count=Math.max(1,(int)Math.ceil((material.pageCount-cursor+1)/(double)slots));int to=Math.min(material.pageCount,cursor+count-1);int from=cursor;List<TopicEntity> covered=topics.findByMaterialIdIn(List.of(material.id)).stream().filter(t->t.slideFrom<=to&&t.slideTo>=from).toList();double base=covered.stream().mapToDouble(t->t.estimatedMinutes*Math.max(0,Math.min(to,t.slideTo)-Math.max(from,t.slideFrom)+1)/(double)(t.slideTo-t.slideFrom+1)).sum();double weight=covered.isEmpty()?1:covered.stream().mapToDouble(t->.8+(t.difficulty+t.importance)/25d).average().orElse(1);int duration=Math.max(10,(int)Math.round(base*weight/5)*5);if(base==0)duration=count*4;
   StudySessionEntity s=new StudySessionEntity();s.id=examId+"-"+days.get(i);s.planId=plan.id;s.examId=examId;s.sessionDate=days.get(i);s.status="planned";s.topic=covered.stream().map(t->t.name).distinct().reduce((a,b)->a+" · "+b).orElse("Studio");s.slideFrom=cursor;s.slideTo=to;s.slidesDone=0;s.nextPage=cursor;s.durationMin=duration;data.save(s);StudyTaskEntity read=new StudyTaskEntity();read.id=s.id+"-read";read.sessionId=s.id;read.taskKind="read";read.label="Studia slide "+cursor+"–"+to;read.durationMin=duration;data.save(read);cursor=to+1;}
  return sessions(examId);}
 public List<SessionDto> sessions(String examId){if(examId!=null)requireExam(examId);List<StudySessionEntity> rows=data.sessions(examId,ownedExamIds());Map<String,List<StudyTaskEntity>> tasks=new HashMap<>();for(var t:data.tasks(rows.stream().map(s->s.id).toList()))tasks.computeIfAbsent(t.sessionId,k->new ArrayList<>()).add(t);return rows.stream().map(s->new SessionDto(s.id,s.examId,s.sessionDate,s.status,s.topic,s.slideFrom,s.slideTo,s.slidesDone,s.nextPage,s.durationMin,s.previousDurationMin,tasks.getOrDefault(s.id,List.of()).stream().map(t->new TaskDto(t.id,t.taskKind,t.label,t.durationMin,t.done,t.meta)).toList(),s.note)).toList();}
 @Transactional public SessionDto toggle(String sessionId,String taskId){StudySessionEntity s=data.session(sessionId);if(s!=null)requireExam(s.examId);StudyTaskEntity t=data.task(taskId);if(s==null||t==null||!t.sessionId.equals(sessionId))throw ApiException.notFound("Attività non trovata");t.done=!t.done;data.save(t);return sessions(s.examId).stream().filter(x->x.id().equals(sessionId)).findFirst().orElseThrow();}
 @Transactional public Map<String,Object> report(String sessionId,String outcome,Integer slidesDone){StudySessionEntity s=data.session(sessionId);if(s!=null)requireExam(s.examId);if(s==null)throw ApiException.notFound("Sessione non trovata");int total=s.slideFrom==null||s.slideTo==null?0:s.slideTo-s.slideFrom+1;s.slidesDone="completed".equals(outcome)?total:"skipped".equals(outcome)?0:Math.min(total,Math.max(0,slidesDone==null?0:slidesDone));s.status=outcome;data.save(s);Map<String,Object> result=new HashMap<>();result.put("session",sessions(s.examId).stream().filter(x->x.id().equals(sessionId)).findFirst().orElseThrow());result.put("adjustment",null);return result;}
 @Transactional public ExamDto availability(String examId,Map<Integer,Integer> availability){ExamEntity e=requireExam(examId);e.availabilityJson=new com.fasterxml.jackson.databind.ObjectMapper().valueToTree(availability).toString();exams.save(e);recalculate(examId);return new it.randyflow.mapper.EntityMapper(new com.fasterxml.jackson.databind.ObjectMapper()).exam(e,materials.findByExamId(examId).stream().map(m->m.id).toList());}
 private ExamEntity requireExam(String id){return exams.findByIdAndOwnerId(id,users.idOrLegacy()).orElseThrow(()->ApiException.notFound("Esame non trovato"));}
 private List<String> ownedExamIds(){return exams.findByOwnerIdOrderByCreatedAtDesc(users.idOrLegacy()).stream().map(e->e.id).toList();}
}
