package it.randyflow.service;

import com.fasterxml.jackson.databind.ObjectMapper; import it.randyflow.domain.*; import it.randyflow.dto.*; import it.randyflow.dto.ApiDtos.*; import it.randyflow.exception.ApiException; import it.randyflow.mapper.EntityMapper; import it.randyflow.repository.*; import jakarta.transaction.Transactional; import java.time.*; import java.util.*; import org.springframework.stereotype.Service;

@Service public class StudyPackageService {
 private final ObjectMapper json; private final StudyPackageValidator validator; private final EntityMapper mapper; private final ExamRepository exams; private final StudyPackageRepository packages; private final StudyMaterialRepository materials; private final TopicRepository topics; private final QuizRepository quizzes; private final FlashcardRepository cards; private final ExamQuestionRepository questions; private final ApplicationRepository data;
 public StudyPackageService(ObjectMapper json,StudyPackageValidator validator,EntityMapper mapper,ExamRepository exams,StudyPackageRepository packages,StudyMaterialRepository materials,TopicRepository topics,QuizRepository quizzes,FlashcardRepository cards,ExamQuestionRepository questions,ApplicationRepository data){this.json=json;this.validator=validator;this.mapper=mapper;this.exams=exams;this.packages=packages;this.materials=materials;this.topics=topics;this.quizzes=quizzes;this.cards=cards;this.questions=questions;this.data=data;}
 public PackagePreview preview(String source){StudyPackageDto p=parse(source);validator.validate(p);var current=packages.findById(p.packageId());if(current.isPresent()&&p.revision()<current.get().revision)throw ApiException.conflict("La revisione è precedente a quella installata");return new PackagePreview(p,summary(p,current.isPresent()));}
 public StudyPackageDto getByExam(String id){return parse(packages.findByExamId(id).orElseThrow(()->ApiException.notFound("Study Package non trovato")).rawJson);}
 public StudyPackageDto getByMaterial(String id){var m=materials.findById(id).orElseThrow(()->ApiException.notFound("Materiale non trovato"));return getByExam(m.examId);}
 public List<StudyPackageDto> list(){return packages.findAll().stream().map(p->parse(p.rawJson)).toList();}
 @Transactional public PackageSummary importPackage(StudyPackageDto p){validator.validate(p);var old=packages.findById(p.packageId());if(old.isPresent()&&p.revision()<old.get().revision)throw ApiException.conflict("La revisione è precedente a quella installata");
  ExamEntity exam=exams.findById(p.exam().id()).orElseGet(ExamEntity::new); boolean newExam=exam.id==null; exam.id=p.exam().id();exam.name=p.exam().name();exam.shortName=p.exam().name().substring(0,Math.min(3,p.exam().name().length())).toUpperCase();exam.description=p.exam().description();if(p.exam().examDate()!=null)exam.examDate=p.exam().examDate();if(exam.examDate==null)exam.examDate=LocalDate.now().plusMonths(1);exam.totalSlides=p.materials().stream().mapToInt(StudyPackageDto.Material::pageCount).sum();if(newExam){exam.createdAt=LocalDate.now();exam.reviewDays=4;exam.availabilityJson="{\"1\":90,\"2\":60,\"3\":90,\"4\":60,\"5\":90}";exam.unavailableDaysJson="[]";}exams.save(exam);
  List<String> previousMaterialIds=materials.findByExamId(exam.id).stream().map(m->m.id).toList();List<String> previousTopicIds=previousMaterialIds.isEmpty()?List.of():topics.findByMaterialIdIn(previousMaterialIds).stream().map(t->t.id).toList();if(!previousTopicIds.isEmpty()){quizzes.deleteByTopicIdIn(previousTopicIds);cards.deleteByTopicIdIn(previousTopicIds);questions.deleteByTopicIdIn(previousTopicIds);topics.deleteByMaterialIdIn(previousMaterialIds);}
  for(var m:p.materials()){StudyMaterialEntity row=materials.findById(m.id()).orElseGet(StudyMaterialEntity::new);row.id=m.id();row.examId=exam.id;row.name=m.name();row.materialType=m.type();row.pageCount=m.pageCount();row.lastPage=Math.max(1,Math.min(row.lastPage,m.pageCount()));row.pagesRead=Math.min(row.pagesRead,m.pageCount());row.updatedAt=LocalDate.now();row.chaptersJson=mapper.write(p.topics().stream().filter(t->t.materialId().equals(m.id())).map(t->new Chapter(t.name(),t.slideRange().from(),t.slideRange().to())).toList());materials.save(row);}
  for(var t:p.topics()){TopicEntity row=new TopicEntity();row.id=t.id();row.materialId=t.materialId();row.name=t.name();row.slideFrom=t.slideRange().from();row.slideTo=t.slideRange().to();row.difficulty=t.difficulty();row.importance=t.importance();row.estimatedMinutes=t.estimatedMinutes();row.simpleExplanation=t.explanations().simple();row.normalExplanation=t.explanations().normal();row.deepExplanation=t.explanations().deep();row.summary=t.summary();row.keyConceptsJson=mapper.write(t.keyConcepts());row.examplesJson=mapper.write(t.examples());topics.save(row);if(data.masteryById(t.id())==null){TopicMasteryEntity mastery=new TopicMasteryEntity();mastery.topicId=t.id();mastery.examId=exam.id;mastery.topicName=t.name();mastery.slideFrom=t.slideRange().from();mastery.slideTo=t.slideRange().to();data.save(mastery);}}
  p.quizzes().forEach(q->{QuizEntity r=new QuizEntity();r.id=q.id();r.topicId=q.topicId();r.quizType=q.type();r.prompt=q.prompt();r.optionsJson=mapper.write(q.options());r.correctAnswer=q.correctAnswer().toString();r.acceptedKeywordsJson=mapper.write(q.acceptedKeywords());r.explanation=q.explanation();r.slideRefsJson=mapper.write(q.slideRefs());quizzes.save(r);});
  p.flashcards().forEach(c->{FlashcardEntity r=new FlashcardEntity();r.id=c.id();r.topicId=c.topicId();r.front=c.front();r.back=c.back();r.slideRefsJson=mapper.write(c.slideRefs());cards.save(r);});
  p.examQuestions().forEach(q->{ExamQuestionEntity r=new ExamQuestionEntity();r.id=q.id();r.topicId=q.topicId();r.prompt=q.prompt();r.modelAnswer=q.modelAnswer();r.evaluationCriteriaJson=mapper.write(q.evaluationCriteria());r.slideRefsJson=mapper.write(q.slideRefs());questions.save(r);});
  StudyPackageEntity stored=old.orElseGet(StudyPackageEntity::new);stored.packageId=p.packageId();stored.examId=exam.id;stored.version=p.version();stored.revision=p.revision();stored.generatedAt=p.generatedAt();stored.language=p.language();stored.rawJson=write(p);stored.importedAt=OffsetDateTime.now();packages.save(stored);return summary(p,old.isPresent());}
 private StudyPackageDto parse(String source){try{return json.readValue(source,StudyPackageDto.class);}catch(Exception e){throw ApiException.badRequest("JSON Study Package non valido: "+e.getMessage());}}
 private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
 private PackageSummary summary(StudyPackageDto p,boolean update){return new PackageSummary(p.packageId(),p.revision(),p.exam().id(),p.exam().name(),p.materials().size(),p.topics().size(),p.quizzes().size(),p.flashcards().size(),p.examQuestions().size(),update);}
}
