package it.randyflow.service;

import com.fasterxml.jackson.databind.ObjectMapper; import it.randyflow.domain.*; import it.randyflow.dto.*; import it.randyflow.dto.ApiDtos.*; import it.randyflow.exception.ApiException; import it.randyflow.mapper.EntityMapper; import it.randyflow.repository.*; import it.randyflow.security.UserContext; import jakarta.transaction.Transactional; import java.time.*; import java.util.*; import org.springframework.stereotype.Service;

@Service public class StudyPackageService {
 private final ObjectMapper json; private final StudyPackageValidator validator; private final EntityMapper mapper; private final ExamRepository exams; private final StudyPackageRepository packages; private final StudyMaterialRepository materials; private final TopicRepository topics; private final QuizRepository quizzes; private final FlashcardRepository cards; private final ExamQuestionRepository questions; private final ApplicationRepository data; private final UserContext users;
 public StudyPackageService(ObjectMapper json,StudyPackageValidator validator,EntityMapper mapper,ExamRepository exams,StudyPackageRepository packages,StudyMaterialRepository materials,TopicRepository topics,QuizRepository quizzes,FlashcardRepository cards,ExamQuestionRepository questions,ApplicationRepository data,UserContext users){this.json=json;this.validator=validator;this.mapper=mapper;this.exams=exams;this.packages=packages;this.materials=materials;this.topics=topics;this.quizzes=quizzes;this.cards=cards;this.questions=questions;this.data=data;this.users=users;}
 public PackagePreview preview(String source){StudyPackageDto p=parse(source);validator.validate(p);var current=packages.findById(key(p.packageId()));if(current.isPresent()&&p.revision()<current.get().revision)throw ApiException.conflict("La revisione è precedente a quella installata");return new PackagePreview(p,summary(p,current.isPresent()));}
 public StudyPackageDto getByExam(String id){requireExam(id);return parse(packages.findByExamId(id).orElseThrow(()->ApiException.notFound("Study Package non trovato")).rawJson);}
 public StudyPackageDto getByMaterial(String id){var m=materials.findById(id).orElseThrow(()->ApiException.notFound("Materiale non trovato"));return getByExam(m.examId);}
 public List<StudyPackageDto> list(){var ids=ownedExamIds();return packages.findAll().stream().filter(p->ids.contains(p.examId)).map(p->parse(p.rawJson)).toList();}
 @Transactional public PackageSummary importPackage(StudyPackageDto input){return importPackage(input,null);}
 @Transactional public PackageSummary importPackage(StudyPackageDto input,String targetExamId){if(targetExamId!=null){requireExam(targetExamId);if(data.sessions(targetExamId,List.of(targetExamId)).isEmpty())throw ApiException.badRequest("Il piano di studio non esiste ancora. Crealo prima di importare il file .study");}validator.validate(input);StudyPackageDto p=targetExamId==null?namespace(input):namespaceForExam(input,targetExamId);var old=packages.findById(p.packageId());if(old.isPresent()&&p.revision()<old.get().revision)throw ApiException.conflict("La revisione è precedente a quella installata");
  if(targetExamId!=null&&old.isPresent()&&!old.get().examId.equals(p.exam().id())){String obsoleteExamId=old.get().examId;data.deleteExamGraph(obsoleteExamId);exams.deleteById(obsoleteExamId);old=Optional.empty();}
  var targetPackage=packages.findByExamId(p.exam().id());if(targetPackage.isPresent()&&!targetPackage.get().packageId.equals(p.packageId()))throw ApiException.conflict("L'esame selezionato ha gi? un altro Study Package");
  ExamEntity exam=exams.findById(p.exam().id()).orElseGet(ExamEntity::new); boolean newExam=exam.id==null;if(!newExam&& !users.idOrLegacy().equals(exam.ownerId))throw ApiException.conflict("Identificatore gi? utilizzato"); exam.id=p.exam().id();exam.ownerId=users.idOrLegacy();if(targetExamId==null||newExam){exam.name=p.exam().name();exam.shortName=p.exam().name().substring(0,Math.min(3,p.exam().name().length())).toUpperCase();exam.description=p.exam().description();if(p.exam().examDate()!=null)exam.examDate=p.exam().examDate();}if(exam.examDate==null)exam.examDate=LocalDate.now().plusMonths(1);exam.totalSlides=p.materials().stream().mapToInt(StudyPackageDto.Material::pageCount).sum();if(newExam){exam.createdAt=LocalDate.now();exam.reviewDays=4;exam.availabilityJson="{\"1\":90,\"2\":60,\"3\":90,\"4\":60,\"5\":90}";exam.unavailableDaysJson="[]";}exams.save(exam);
  List<String> previousMaterialIds=materials.findByExamId(exam.id).stream().map(m->m.id).toList();List<String> previousTopicIds=previousMaterialIds.isEmpty()?List.of():topics.findByMaterialIdIn(previousMaterialIds).stream().map(t->t.id).toList();if(!previousTopicIds.isEmpty()){quizzes.deleteByTopicIdIn(previousTopicIds);cards.deleteByTopicIdIn(previousTopicIds);questions.deleteByTopicIdIn(previousTopicIds);topics.deleteByMaterialIdIn(previousMaterialIds);}
  for(var m:p.materials()){StudyMaterialEntity row=materials.findById(m.id()).orElseGet(StudyMaterialEntity::new);row.id=m.id();row.examId=exam.id;row.name=m.name();row.materialType=m.type();row.pageCount=m.pageCount();row.lastPage=Math.max(1,Math.min(row.lastPage,m.pageCount()));row.pagesRead=Math.min(row.pagesRead,m.pageCount());row.updatedAt=LocalDate.now();row.chaptersJson=mapper.write(p.topics().stream().filter(t->t.materialId().equals(m.id())).map(t->new Chapter(t.name(),t.slideRange().from(),t.slideRange().to())).toList());materials.save(row);}
  for(var t:p.topics()){TopicEntity row=new TopicEntity();row.id=t.id();row.materialId=t.materialId();row.name=t.name();row.pageType=t.pageType()==null?"content":t.pageType();row.slideFrom=t.slideRange().from();row.slideTo=t.slideRange().to();row.difficulty=t.difficulty();row.importance=t.importance();row.estimatedMinutes=t.estimatedMinutes();row.simpleExplanation=t.explanations().simple();row.normalExplanation=t.explanations().normal();row.deepExplanation=t.explanations().deep();row.summary=t.summary();row.keyConceptsJson=mapper.write(t.keyConcepts());row.examplesJson=mapper.write(t.examples());topics.save(row);if(data.masteryById(t.id())==null){TopicMasteryEntity mastery=new TopicMasteryEntity();mastery.topicId=t.id();mastery.examId=exam.id;mastery.topicName=t.name();mastery.slideFrom=t.slideRange().from();mastery.slideTo=t.slideRange().to();data.save(mastery);}}
  p.quizzes().forEach(q->{QuizEntity r=new QuizEntity();r.id=q.id();r.topicId=q.topicId();r.quizType=q.type();r.prompt=q.prompt();r.optionsJson=mapper.write(q.options());r.correctAnswer=q.correctAnswer().toString();r.acceptedKeywordsJson=mapper.write(q.acceptedKeywords());r.explanation=q.explanation();r.slideRefsJson=mapper.write(q.slideRefs());quizzes.save(r);});
  p.flashcards().forEach(c->{FlashcardEntity r=new FlashcardEntity();r.id=c.id();r.topicId=c.topicId();r.front=c.front();r.back=c.back();r.slideRefsJson=mapper.write(c.slideRefs());cards.save(r);});
  p.examQuestions().forEach(q->{ExamQuestionEntity r=new ExamQuestionEntity();r.id=q.id();r.topicId=q.topicId();r.prompt=q.prompt();r.modelAnswer=q.modelAnswer();r.evaluationCriteriaJson=mapper.write(q.evaluationCriteria());r.slideRefsJson=mapper.write(q.slideRefs());questions.save(r);});
  StudyPackageEntity stored=old.orElseGet(StudyPackageEntity::new);stored.packageId=p.packageId();stored.examId=exam.id;stored.version=p.version();stored.revision=p.revision();stored.generatedAt=p.generatedAt();stored.language=p.language();stored.rawJson=write(p);stored.importedAt=OffsetDateTime.now();packages.save(stored);return summary(p,old.isPresent());}
 private ExamEntity requireExam(String id){return exams.findByIdAndOwnerId(id,users.idOrLegacy()).orElseThrow(()->ApiException.notFound("Esame non trovato"));}
 private List<String> ownedExamIds(){return exams.findByOwnerIdOrderByCreatedAtDesc(users.idOrLegacy()).stream().map(e->e.id).toList();}
 private String key(String id){return "local".equals(users.idOrLegacy())?id:users.idOrLegacy()+"::"+id;}
 private StudyPackageDto namespaceForExam(StudyPackageDto input,String targetExamId){
  ExamEntity target=exams.findByIdAndOwnerId(targetExamId,users.idOrLegacy()).orElseThrow(()->ApiException.notFound("Esame non trovato"));
  StudyPackageDto p=namespace(input);List<StudyMaterialEntity> existing=materials.findByExamId(target.id);Map<String,String> materialIds=new HashMap<>();
  for(int i=0;i<p.materials().size();i++)materialIds.put(p.materials().get(i).id(),i<existing.size()?existing.get(i).id:p.materials().get(i).id());
  var mappedMaterials=p.materials().stream().map(m->new StudyPackageDto.Material(materialIds.get(m.id()),m.name(),m.type(),m.pageCount())).toList();
  var mappedTopics=p.topics().stream().map(t->new StudyPackageDto.Topic(t.id(),materialIds.get(t.materialId()),t.name(),t.pageType(),t.slideRange(),t.difficulty(),t.importance(),t.estimatedMinutes(),t.explanations(),t.summary(),t.keyConcepts(),t.examples(),t.quizIds(),t.flashcardIds(),t.examQuestionIds())).toList();
  return new StudyPackageDto(p.format(),p.version(),p.packageId(),p.revision(),p.generatedAt(),p.language(),new StudyPackageDto.Exam(target.id,target.name,target.description,target.examDate),mappedMaterials,mappedTopics,p.quizzes(),p.flashcards(),p.examQuestions());
 }
 private StudyPackageDto namespace(StudyPackageDto p){if("local".equals(users.idOrLegacy())||p.packageId().startsWith(users.idOrLegacy()+"::"))return p;java.util.function.Function<String,String> k=this::key;return new StudyPackageDto(p.format(),p.version(),k.apply(p.packageId()),p.revision(),p.generatedAt(),p.language(),new StudyPackageDto.Exam(k.apply(p.exam().id()),p.exam().name(),p.exam().description(),p.exam().examDate()),p.materials().stream().map(m->new StudyPackageDto.Material(k.apply(m.id()),m.name(),m.type(),m.pageCount())).toList(),p.topics().stream().map(t->new StudyPackageDto.Topic(k.apply(t.id()),k.apply(t.materialId()),t.name(),t.pageType(),t.slideRange(),t.difficulty(),t.importance(),t.estimatedMinutes(),t.explanations(),t.summary(),t.keyConcepts(),t.examples(),t.quizIds().stream().map(k).toList(),t.flashcardIds().stream().map(k).toList(),t.examQuestionIds().stream().map(k).toList())).toList(),p.quizzes().stream().map(q->new StudyPackageDto.Quiz(k.apply(q.id()),k.apply(q.topicId()),q.type(),q.prompt(),q.options(),q.correctAnswer(),q.acceptedKeywords(),q.explanation(),q.slideRefs())).toList(),p.flashcards().stream().map(c->new StudyPackageDto.Flashcard(k.apply(c.id()),k.apply(c.topicId()),c.front(),c.back(),c.slideRefs())).toList(),p.examQuestions().stream().map(q->new StudyPackageDto.ExamQuestion(k.apply(q.id()),k.apply(q.topicId()),q.prompt(),q.modelAnswer(),q.evaluationCriteria(),q.slideRefs())).toList());}
 private StudyPackageDto parse(String source){try{return json.readValue(source,StudyPackageDto.class);}catch(Exception e){throw ApiException.badRequest("JSON Study Package non valido: "+e.getMessage());}}
 private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
 private PackageSummary summary(StudyPackageDto p,boolean update){return new PackageSummary(p.packageId(),p.revision(),p.exam().id(),p.exam().name(),p.materials().size(),p.topics().size(),p.quizzes().size(),p.flashcards().size(),p.examQuestions().size(),update);}
}
